<?php if ($this->id && $this->size && $this->slot) { ?>
    <div class='dfp' min-width="<?= $this->min_width ?>" max-width="<?= $this->max_width ?>" data-id='<?= $this->id ?>' data-size='<?= $this->size ?>' data-slot='<?= $this->slot ?>'></div>
<?php } else { ?>
    <!-- Nenhum banner encontrado para este espaço (<?= $this->size_details->size ?> <?= $this->size_details->width ?>x<?= $this->size_details->height ?>) -->
<?php } ?>