<?php if ($this->id && $this->size && $this->slot) { ?>
    <div class="wraper-<?= strtolower(str_replace(' ', '_', $this->size_details->size)) ?>">
        <div class='<?= strtolower(str_replace(' ', '_', $this->size_details->size)) ?> dfp' min-width="<?= $this->min_width? : '0' ?>" max-width="<?= $this->max_width? : '0' ?>" data-id='<?= $this->id ?>' data-size='<?= $this->size ?>' data-slot='<?= $this->slot ?>'></div>
    </div>    
<?php } else { ?>
                <!-- Nenhum banner encontrado para este espaço (<?= $this->size_details->size ?> <?= $this->size_details->width ?>x<?= $this->size_details->height ?>) -->
<?php } ?>