<nav class="breadcrumbs">
    <ul>
        <li>
            <a href="<?= admin_url('admin.php?page=DoubleClick'); ?>">Double Click</a>        
        </li>        
    </ul>
</nav>
<div class="wrap">
    <h2>Settings</h2>    
</div>
<div class="wrap">
    <h2>Double Click</h2>    
    <table class="form-table">
        <tr valign="top">
        <form method="post" action="<?= $_SERVER['REQUEST_URI'] ?>&action=dfpSizes">        
            <th scope="row">Peças</th>
            <td>                    
                <?php print_r($this->dfpSizes); ?>
            </td>
            <td>                    
                <?php submit_button('Adicionar Peça'); ?>
            </td>
        </form>
        </tr>
        <tr valign="top">
        <form method="post" action="<?= $_SERVER['REQUEST_URI'] ?>&action=page">        
            <th scope="row">Paginas:</th>
            <td>                    
                Páginas Aqui
            </td>
            <td>
                <?php submit_button('Adicionar Peça'); ?>

            </td>
        </form>
        </tr>                        
    </table>  

</div>