<div class="wrap">
    <h2>Adicionar Peças na URL</h2>
    <form method="post" action="<?= $_SERVER['REQUEST_URI'] ?>&action=addPage">
        <table class="form-table">
            <tr valign="top">
                <th scope="row">Optimize Admin?</th>
                <td>
                    <input type="radio" id="OptimizeAdmin" name="OptimizeAdmin" <?= esc_attr(get_option('OptimizeAdmin')) ? 'checked="checked"' : ''; ?> value="1" />Yes
                    <input type="radio" id="OptimizeAdmin" name="OptimizeAdmin" <?= esc_attr(get_option('OptimizeAdmin')) ? '' : 'checked="checked"'; ?> value="0" />No
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Peça:</th>
                <td>                    
                    <input type="radio" id="peca" name="APP_ENV" <?= (esc_attr(get_option('APP_ENV')) == 'production') ? 'checked="checked"' : ''; ?> value="production" />Production
                    <input type="radio" id="peca" name="APP_ENV" <?= (esc_attr(get_option('APP_ENV')) == 'production') ? '' : 'checked="checked"'; ?> value="development" />Development
                </td>
            </tr>
            <tr valign="top">
                <th scope="row">Categorias:</th>
                <td>
                    <ul>
                        <?php wp_category_checklist(null, null, array(1,3)); ?>
                    </ul>
                </td>
            </tr>                        
        </table>  
        <?php submit_button('Adicionar URL'); ?>
    </form>
</div>